# Generated by Django 5.0.3 on 2024-03-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
